import Head from "next/head";
//import Navbar from './Navbar';
//import Footer from './Footer';
//import Footer from "../components/footer/FooterAdmin";

export default function Layout({ children }) {
  return (
    <>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="min-h-full">
      <main>
        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          {/* Replace with your content */}
          {children}
          {/* /End replace */}
        </div>
      </main>
      
    </div>
       
    </>
  )
}